
package localdbservices.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EntitiesService", targetNamespace = "http://soap.localdbservices/", wsdlLocation = "http://localhost:9004/ws/virtuallifecoach/entities?wsdl")
public class EntitiesService
    extends Service
{

    private final static URL ENTITIESSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENTITIESSERVICE_EXCEPTION;
    private final static QName ENTITIESSERVICE_QNAME = new QName("http://soap.localdbservices/", "EntitiesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9004/ws/virtuallifecoach/entities?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTITIESSERVICE_WSDL_LOCATION = url;
        ENTITIESSERVICE_EXCEPTION = e;
    }

    public EntitiesService() {
        super(__getWsdlLocation(), ENTITIESSERVICE_QNAME);
    }

    public EntitiesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTITIESSERVICE_QNAME, features);
    }

    public EntitiesService(URL wsdlLocation) {
        super(wsdlLocation, ENTITIESSERVICE_QNAME);
    }

    public EntitiesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTITIESSERVICE_QNAME, features);
    }

    public EntitiesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntitiesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Entities
     */
    @WebEndpoint(name = "EntitiesImplPort")
    public Entities getEntitiesImplPort() {
        return super.getPort(new QName("http://soap.localdbservices/", "EntitiesImplPort"), Entities.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Entities
     */
    @WebEndpoint(name = "EntitiesImplPort")
    public Entities getEntitiesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.localdbservices/", "EntitiesImplPort"), Entities.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTITIESSERVICE_EXCEPTION!= null) {
            throw ENTITIESSERVICE_EXCEPTION;
        }
        return ENTITIESSERVICE_WSDL_LOCATION;
    }

}
